### PR TITLE
Update GHC and Cabal bounds

### PR DESCRIPTION
**Pull request by rockbmb**
WIP, this PR will also include CI for this repository, plus whatever fixes are needed to work with recent versions of GHC and Cabal.

### CODE REVIEW

**Comment by Bodigrim** [comment]
Offtop: is is possible to raise an issue in a forked repo?

**Comment by rockbmb** [comment]
@Bodigrim Argh, thanks for pointing that out. I don't know the answer to that question right now.

I just noticed there are no issues here. At worst, should there be no way of creating them here, you can just do so in the original repository and mention me so I can be aware.

**Comment by Bodigrim** [comment]
AFAIU you can [duplicate](https://help.github.com/articles/duplicating-a-repository/) repo. This also has an advantage that people would send PRs here instead of original repo.

**Comment by rockbmb** [comment]
Although this PR was made from the fork to be merged to the fork, I did not know GitHub allowed repository duplication. Thanks, I'll do that instead.

**Comment by rockbmb** [comment]
@Bodigrim created a mirrored repository, you should be able to submit issues now.
rockbmb/gamma2#1

**Pull request closed without merging**
